name: Build the application

on:
  push:
    branches:
      - main
      - locale/*
      - feature/*
      - fix/*
    paths-ignore:
      - 'layout/**'
      - 'TSH.exe'
  workflow_dispatch:

jobs:
  build:
    name: Generate Windows Release
    runs-on: ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/heads/feature/' ) || startsWith( github.ref, 'refs/heads/fix/' ) }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - run: pip install -r dependencies/requirements.txt pyinstaller
      - run: |
          set PYTHONUTF8=1
          chcp 65001
          set PYTHONIOENCODING=utf-8
          python scripts/gen_contributors.py
          pyinstaller --hidden-import=loguru --hidden-import=engineio.async_drivers.threading main.py --onefile -w --icon assets\icons\Hammer.ico
          copy dist\main.exe Voidscape.exe

      - run: git pull
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Voidscape.exe
          git commit -m "Update EXE" -a

      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
